export const fieldNames = [
  'studentId',
  'aadharNo',
  'PENNo',
  'GRN',
  'name',
  'fathersName',
  'surname',
  'mothersName',
  'religion',
  'caste',
  'subCaste',
  'placeOfBirth',
  'taluka',
  'district',
  'state',
  'dateOfBirth',
  'lastAttendedSchool',
  'lastSchoolStandard',
  'dateOfAdmission',
  'admissionStandard',
  'nationality',
  'motherTongue'
]

export const fieldLabels = {
  studentId: 'Student ID',
  aadharNo: 'Aadhar Number',
  PENNo: 'PEN Number',
  GRN: 'GRN',
  name: 'Name',
  fathersName: "Father's Name",
  surname: 'Surname',
  mothersName: "Mother's Name",
  religion: 'Religion',
  caste: 'Caste',
  subCaste: 'Sub-caste',
  placeOfBirth: 'Place of Birth',
  taluka: 'Taluka',
  district: 'District',
  state: 'State',
  dateOfBirth: 'Date of Birth',
  lastAttendedSchool: 'Last Attended School',
  lastSchoolStandard: 'Last School Standard',
  dateOfAdmission: 'Date of Admission',
  admissionStandard: 'Admission Standard',
  nationality: 'Nationality',
  motherTongue: 'Mother Tongue'
}

export const dateFields = ['dateOfBirth', 'dateOfAdmission']

export const dialogOptions = {
  religion: ['Hindu', 'Islam', 'Christianity', 'Sikhism', 'Buddhism'],
  state: [
    'Maharashtra',
    'Gujarat',
    'Madhya Pradesh',
    'Goa',
    'Karnataka',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Kerala',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal'
  ],
  district: [
    'Jalgaon',
    'Mumbai City',
    'Mumbai Suburban',
    'Pune',
    'Thane',
    'Nagpur',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Latur',
    'Akola',
    'Chandrapur',
    'Parbhani',
    'Yavatmal',
    'Satara',
    'Sangli',
    'Wardha',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalna',
    'Nanded',
    'Nandurbar',
    'Osmanabad',
    'Raigad',
    'Ratnagiri',
    'Sindhudurg',
    'Washim'
  ],
  nationality: ['Indian'],
  admissionStandard: ['V', 'VI', 'VII', 'VIII', 'IX', 'X'],
  lastSchoolStandard: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'],
  motherTongue: ['Marathi', 'Hindi', 'English', 'Gujarati', 'Urdu']
}
